### ISSUE TITLE
写高考作文吗？

### ISSUE THREAD

**Issue by GzhiYi** [lesywix/LCTM#2]
又回到最初的起点
记忆中你青涩的脸
我们终于
来到了这一天
桌垫下的老照片
无数回忆连结
今天男孩要赴女孩最后的约
又回到最初的起点
呆呆地站在镜子前
笨拙系上红色领带的结
将头发梳成大人模样
穿上一身帅气西装
等会儿见你一定比想像美
好想再回到那些年的时光
回到教室座位前后
故意讨你温柔的骂
黑板上排列组合
你舍得解开吗
谁与谁坐他又爱着她
那些年错过的大雨
那些年错过的爱情
好想拥抱你
拥抱错过的勇气
曾经想征服全世界
到最后回首才发现
这世界滴滴点点全部都是你
那些年错过的大雨
那些年错过的爱情
好想告诉你
告诉你我没有忘记
那天晚上满天星星
平行时空下的约定
再一次相遇我会
紧紧抱着你
紧紧抱着你
又回到最初的起点
呆呆地站在镜子前
笨拙系上红色领带的结
将头发梳成大人模样
穿上一身帅气西装
等会儿见你一定比想像美
好想再回到那些年的时光
回到教室座位前后
故意讨你温柔的骂
黑板上排列组合
你舍得解开吗
谁与谁坐他又爱着她
那些年错过的大雨
那些年错过的爱情
好想拥抱你
拥抱错过的勇气
曾经想征服全世界
到最后回首才发现
这世界滴滴点点全部都是你
那些年错过的大雨
那些年错过的爱情
好想告诉你
告诉你我没有忘记
那天晚上满天星星
平行时空下的约定
再一次相遇我会
紧紧抱着你
紧紧抱着你

**Comment by lesywix** [comment]
没有任何这个意思 🕶

**Comment by GzhiYi** [comment]
dd
